version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      barcode-runtime:
        patterns:
          - barcode-detector
          - zxing-wasm
        dependency-type: production
        update-types:
          - minor
          - patch
      production-minor-patch:
        exclude-patterns:
          - barcode-detector
          - zxing-wasm
        dependency-type: production
        update-types:
          - minor
          - patch
      development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
